/**
 * Generated by scripts/fetch-tiktok-stats.mjs. Do not edit by hand.
 *
 * Refreshed on a schedule by .github/workflows/tiktok-stats.yml, which commits
 * only when a number actually changes.
 */

export const tiktokStats = {
  followerCount: 11900,
  heartCount: 1300000,
  videoCount: 57,
  fetchedAt: "2026-09-21",
};
